name: reclaimed
favicon: null
layout_spectrum: 0.9728281036950648
typography_spectrum: 0.028859924292191863
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5119446634780616
  lightness: 0.14862772705964744
  saturation: 0.7703651050105691
  rhythmicContrast: 0.5455856793560088
purpose: []
